version: 2
jobs:
  build:
    working_directory: ~/circleci-feature9
    docker:
      - image: maven:3.8.5-openjdk-17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: circleci-feature9-{{ checksum "pom.xml" }}
      - run:
          command: |
            mvn install -DskipITs=true
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-feature9-{{ checksum "pom.xml" }}
